### ISSUE TITLE
Map Details not Displayed Properly on GPS

### ISSUE THREAD

**Issue by flywire** [bazuchan/geotiff2rmp#1]
Poor cvg_map.msf format does not display map details properly on GPS.
- fix geotiff2rmp.py: craft_description_file.
  
  `def craft_description_file(self):`
       `descfile = ';Map Support File: Contains Meta Data Information about the Image\r\n'`
       `descfile += 'IMG_NAME = %s\r\n' % (self.map_name) # Name of map displayed not filename`
       `descfile += 'PRODUCT = %s\r\n' % (self.map_group)`
       `descfile += 'PROVIDER = %s\r\n' % (self.map_prov)`
       `descfile += 'IMG_DATE = %s\r\n' % (time.strftime('%d.%m.%Y %H:%M:%S'))`
       `descfile += 'IMG_VERSION = %s\r\n' % (self.map_ver)`
       `descfile += 'MAP_COUNT = %s\r\n' % (self.map_count)`
       `descfile += 'IMAGE_BB = %s\r\n' % (self.map_bbox('????')) # %f, %f' % tl, %f, %f' % br - test`
       `descfile += 'Version = 31\r\n'    # this line is a bug`
       `descfile += 'BUILD=\r\n'          # this line serves no purpose`
       `descfile += 'VENDOR_ID = -1\r\n'  # this line serves no purpose`
       `descfile += 'REGION_ID = -1\r\n'  # this line serves no purpose`
       `descfile += 'MAP_TYPE = TNDB_RASTER_MAP\r\n'`
       `descfile += 'COPY_RIGHT_INFO = %s\r\n' % (self.map_cprt) # if cprt_txt.txt not supported`
       `descfile += 'COPY_RIGHT_LOCATION = cprt_txt.txt\r\n'`
      `descfile += 'CONTACT_INFO = %s\r\n' % (self.map_contact)`
       `descfile += 'ADDITIONAL_COMMENTS = Created with geotiff2rmp.py\r\n'`
      `self.rmpfile.append_from_string('cvg_map.msf', descfile)`
  
  `def craft_resourse_files(self):`
       `for i in ['chunk.ics', 'BMP4BIT.ICS', 'cprt_txt.txt']:`
           `self.rmpfile.append_from_file(i, self.resdir + '/' + i)``
- Reference: (http://tourist.kharkov.ua/phpbb/viewtopic.php?f=118&t=62113&start=225#p1536896)

**Comment by bazuchan** [comment]
I have added above parameters except IMAGE_BB (calculating it will add unneeded complexity). Will you be willing to test?

**Comment by flywire** [comment]
Yes, I will test. Triton 2000 and eX710.

Regards

**Comment by flywire** [comment]
Willing but technically challenged with environment.

https://github.com/flywire

**Comment by flywire** [comment]
Win7-32
Deleted 1st line of geotiff2rmp.py and install gdal directory under current directory
Execute program as below
Output is SI55.rmp consisting of H1828 H00 bytes, H00 byte, chunk.ics, BMP4BIT.ICS, (C) notice.

C:>python geotiff2rmp.py -o SI55.rmp SI55.tif
[0.0%------------------------------------------------------------------]The syst
em cannot find the path specified.
Traceback (most recent call last):
  File "geotiff2rmp.py", line 594, in <module>
    converter.run()
  File "geotiff2rmp.py", line 562, in run
    offsets = self.craft_tiles(rmap, self.idx, tiles_offset, tiles_size)
  File "geotiff2rmp.py", line 528, in craft_tiles
    tile = open(self.temp_tile).read()
IOError: [Errno 2] No such file or directory: 'SI55.rmp.tile0'

**Comment by flywire** [comment]
It would be useful to run in debug mode. geotiff2rmp.py has more dependencies. Maybe test unpackrmp.py and tlm2text.py first then gdal/rasterio.

**Comment by bazuchan** [comment]
Checkout latest version, I fixed working under windows with gdal binaries.

**Comment by flywire** [comment]
From my path: Path=...;C:\Python27\;C:\Python27\Scripts;...
Can I leave the first line under windows?
I want to test in parts. Can you email me? Check my profile.

C:...\geotiff2rmp-master>python geotiff2rmp.py -o SI55.rmp SI55.tif
[0.0%------------------------------------------------------------------]Traceback (most recent call last):
  File "geotiff2rmp.py", line 595, in <module>
    converter.run()
  File "geotiff2rmp.py", line 563, in run
    offsets = self.craft_tiles(rmap, self.idx, tiles_offset, tiles_size)
  File "geotiff2rmp.py", line 529, in craft_tiles
    tile = self.crop_image(self.temp_tile, tw, th, xpad, ypad)
  File "geotiff2rmp.py", line 510, in crop_image
    new = new_img.save(o_img, 'JPEG')
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1439, in save
    save_handler(self, fp, filename)
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 471, in _save
    ImageFile._save(im, fp, [("jpeg", (0,0)+im.size, 0, rawmode)])
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 476, in _save
    fh = fp.fileno()
io.UnsupportedOperation: fileno

C:...\geotiff2rmp-master>
