### ISSUE TITLE
packrmp can't find geotiff2rmp in path

### ISSUE THREAD

**Issue by flywire** [bazuchan/geotiff2rmp#3]
C:...\geotiff2rmp-master>python debug\packrmp.py SK55Tpo1.rmp_unpack SK55Tpo2.rmp
Traceback (most recent call last):
  File "debug\packrmp.py", line 5, in <module>
    import geotiff2rmp
ImportError: No module named geotiff2rmp

**Comment by bazuchan** [comment]
Fixed

**Comment by flywire** [comment]
C:...\geotiff2rmp>python debug\packrmp.py SK55Tpo1.rmp_unpack SK55Tpo2.rmp
Traceback (most recent call last):
  File "debug\packrmp.py", line 9, in <module>
    import geotiff2rmp
ImportError: No module named geotiff2rmp

Win7-32

**Comment by bazuchan** [comment]
Fix again

**Comment by flywire** [comment]
Working but one message to fix. (Not tested on GPS.) Off to bed for me.

C:...\geotiff2rmp>python debug\unpackrmp.py SK55Tpo5.rmp
Unpacking bmp2bit.ics
Unpacking bmp4bit.ics
Unpacking cprt_txt.txt
Unpacking cvg_map.msf
Unpacking rmp.ini
Unpacking topo0.a00
Unpacking topo0.tlm

C:...\geotiff2rmp>python debug\packrmp.py SK55Tpo5.rmp_unpack SK55Tpo6.rmp
_Using dgal module and binaries (Slow!)  << I don't think so_

Regards

**Comment by bazuchan** [comment]
removed message when geotiff2rmp used as module
